language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer self-update
  - composer install --no-interaction

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit ./tests
  - vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1 --standard=phpcs.xml src
  - vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1 --standard=phpcs.xml tests
